### ISSUE TITLE
Bad Request on talk()

### ISSUE THREAD

**Issue by dbaltas** [Nexmo/nexmo-php#103]
Hello,

The code below is used to create a talk and send text to a phone number.
The call is created successfully, but I get a `400, bad request` from `Nexmo\Call\Talk->put()` method.

```php
  $basic  = new \Nexmo\Client\Credentials\Basic(API_KEY, API_SECRET);
  $keypair = new \Nexmo\Client\Credentials\Keypair(file_get_contents(PRIVATE_KEY_PATH), APP_ID);

  $client = new \Nexmo\Client(new \Nexmo\Client\Credentials\Container($basic, $keypair));

  $call = $client->calls()->create([
    'to' => [[
      'type' => 'phone',
      'number' => NEXMO_TO
    ]],
    'from' => [
      'type' => 'phone',
      'number' => NEXMO_FROM
    ],
    'answer_url' => ['https://httpstat.us/200'],
    'event_url' => ['https://httpstat.us/200'],
  ]);

  $talk = new Talk($call->getId());
  $talk->setClient($client);
  $talk->setText("Hi, this is Russell. You are listening to a text-to-speech Call made with Nexmo's Voice API");
  $response = $talk->put();
```

**Comment by mheap** [comment]
Hey @dbaltas,

I've recreated the issue that you're encountering. This is happening because the call is not active when you call `$talk->put()`. There are two ways to solve this:

1. Wait until you receive the `answered` event on your `event_url` and use the `Talk` action on the call then
2. Create a [talk NCCO](https://developer.nexmo.com/api/voice/ncco#talk), serve it on a URL and use that as your `answer_url`

**Comment by dbaltas** [comment]
Thank you!
