### ISSUE TITLE
authentication failed

### ISSUE THREAD

**Issue by sebishabeeb** [Nexmo/nexmo-php#118]
hi iam beginner in nexmo. i just installed through sdk tools (php).then i search available numbers and i got some numbers. then i try to purchase a number then show authentication failed
my code:

<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Nexmo; 
class DashboardController extends Controller
{
  
    public function index(Request $request)
    {
        $basic  = new \Nexmo\Client\Credentials\Basic(env('NEXMO_KEY'), env('NEXMO_SECRET'));
        $client = new \Nexmo\Client($basic);
        $nums =  $client->numbers()->searchAvailable('US'); 
        try
        {
         $prch = $client->numbers()->purchase($nums[0], 'US');
        } catch (\Exception $e) {
          return $e;
        }
      
    }

**Comment by lornajane** [comment]
Thanks for opening an issue to let us know about this problem.  Before the `try{` part, can you check that `$nums` contains some data?  Also you will need to have added credit to your account in order to purchase a number - the initial Nexmo credit is just for you to test some calls/messages. If you can let us have the answers to these questions, hopefully we can help further - let us know how you get on!

**Comment by lornajane** [comment]
Closed due to inactivity but please let us know if you need anything else

**Comment by JackSparroow** [comment]
Hey @lornajane ! Currently I'm using Vonage API in one of  my project. Meanwhile  I'm using Trial account for the initial stage. However, I'm facing an issue regarding the api response. I knew that trial account doesn't alllow to purchase number. When  I call API to buy a number, it returns authentication failed error that doesn't make sense.  Even every API end point with the same API Key and Secret is working perfect.  When I call buy number API, instead of successful response it returns 401 authentication failed error that should not be. In case of Trial account, it should return success response with message something like "You can't purchase with Trial Account" so it doesn't create any confusion for developers. Still I'm confused is there something wrong  with the API I calling or the 401 is actually showing the response for trial account.  Kindly check it please.

Thanks,

**Comment by dragonmantank** [comment]
> Still I'm confused is there something wrong with the API I calling or the 401 is actually showing the response for trial account. Kindly check it please.

Hello @JackSparroow! During the trial phase, there are [a few restrictions](https://help.nexmo.com/hc/en-us/articles/212554438) on the account, and as you mentioned purchasing numbers is one of them. A `4xx` error is more appropriate in this case than a `200 OK` message, as your request did in fact fail (though I can see an argument between `401` and `403`).

In this case though, `401 Unauthorized` is probably the most appropriate. It can be a bit confusing because the credentials do work in other places, but until the account is upgraded a `401` response gives the clearest indication that purchasing numbers is not authorized. 

Once your account has been upgraded to a paid account, purchasing numbers will be authorized.

**Comment by JackSparroow** [comment]
Hi @dragonmantank ! Thank you for your feedback.  Sorry but this is not good approach. 

**The `401` Unauthorized error is an HTTP status code that means the page you were trying to access cannot be loaded until you first log in with a valid user ID and password. If you've just logged in and received the 401 Unauthorized error, it means that the credentials you entered were invalid for some reason**

According to this, If I call my Vonage API and If it doesn't passed the correct credentials like API Key & API Secret then definitely it make sense to return 401 unauthorized error because I don't have access to my vonage Communication portal. But in this case of calling Vonage Purchase API, It actually authenticating all the credentials and reaching my vonage api portal. Now We can never say that the request should return 401 Unauthorized. Does it make sense ? _Even developer is confused sitting on the desk and thinking that may be the api key or secret passing along with API parameters are wrong that's why the request is not authorized_

Sorry Respected Sir, It is not the correct way. The API must return the success status 200 or 400 but the error message should notify the user that "You are unable to purchase number with trial account" So that he can understand that API is working perfect and he should upgrade his account. I integrated Twilio API before the Vonage API and even they are returning the status code 400 and message saying that "Trial Accounts are allowed only one Twilio Number. To purchase additional number please upgrade you account". Now the developers will easily understand and will never get confused. Even I spend more than one hour to figure out this what exactly the issue is.

**Comment by dragonmantank** [comment]
Thanks for the feedback! I'll send these along to the API team, but can't make any guarantees on if/when changes will be made.
