### ISSUE TITLE
Please i need Help Nexmo to setup sms reminder

### ISSUE THREAD

**Issue by YAHTECHGH** [Nexmo/nexmo-php#165]
Please i need help to set up an SMS reminder. how to add DATE and TIME to response to the command. or for the person to received it on specific time and date, Please i need to help to setup on my Nexmo Account. THANK YOU.

**Comment by lornajane** [comment]
Hi @YAHTECHGH , we don't offer timed sending at Nexmo but I have some suggestions that I hope will help you.

There are some examples of sending an SMS here https://developer.nexmo.com/messaging/sms/code-snippets/send-an-sms.

For the timed part, you might find it useful to use a cron job https://en.wikipedia.org/wiki/Cron - but this is not a Nexmo feature, it is something you will need to set up yourself.

Good luck with your project, I will close this issue since there is no bug with the code.
