### ISSUE TITLE
Undefine Index: national _format_number

### ISSUE THREAD

**Issue by bbashel1** [Nexmo/nexmo-php#174]
I have implemented the following code to check a phone number is valid or not.

$basic  = new \Nexmo\Client\Credentials\Basic(config('service.nexmo.key'), config('service.nexmo.secret'));
        $client = new \Nexmo\Client($basic);
        $new_phone = $phone;
        if (substr($phone, 0, 2) == '00') {
            $new_phone =  substr($phone, 2);
         }elseif(substr($phone, 0, 1) == '0' && substr($phone, 0, 2) !== '00'){
             $new_phone = substr($phone, 1);
         }
         try{
            $insights = $client->insights()->advanced($new_phone);
            if($insights['valid_number'] === "valid"){
                return true;
            }
         }catch(\ErrorException $e){
             return false;
         }
Whichever number I try I always get the same error. It was working well and certainly, I started getting
 `ErrorException (E_NOTICE)
Undefined index: national_format_number`

**Comment by lornajane** [comment]
It's hard to say what is happening here but we are aware that sometimes the synchronous requests to the advanced Number Insights endpoints can time out.

The best thing to do would be to use the Asynchronous version of the API https://developer.nexmo.com/api/number-insight#getNumberInsightAsync since this won't have the timeout issues.

Perhaps a faster thing to try first is to check what the API response is, for example if you add these lines after the call to `$client->insights()->advanced()`:

```
    echo "Status: " . $insights['status'] . "\n"; 
    echo $insights['status_message'] . "\n"; 
```

This should show you any error (status should be zero if the request is successful) and the details are in the message.
