### ISSUE TITLE
does not handle POST/JSON, only POST or GET

### ISSUE THREAD

**Issue by Cyrille37** [Nexmo/nexmo-php#33]
Hi,

In [dashboard nexmo settings](https://dashboard.nexmo.com/settings) we can set API Settings HTTP Method to "**POST-JSON**" but the nexmo-php library does not handle this type.
I did not find this limitation in documentation.

To had this feature just case on "content-type" like with "POST-JSON" it has value "application/json;charset=UTF-8". Should I purpose a PR or not ?

Cheers.

**Comment by tjlytle** [comment]
@Cyrille37 I don't want to discourage PRs, and you're right `Nexmo\Message\InboundMessage::createFromGlobals()` could work with JSON as well as `application/x-www-form-urlencoded` by evaluating the `content-type`.

However, I'm cautious about adding additional code for different formats of essentially the same data. If you're using the client library, it turns the inbound request (whatever the format) into an object with array access. Since that would happen regardless of format, why support both?

There's already essentially duplicative code for supporting JSON / URL Encoded / Query String as payloads _to_ the API (code I hope to one day remove).

So I'd like to know a bit more of the value behind adding this support. Is `POST/JSON` now the default for new numbers? @leggetter I'm out of the loop on this one, is this something all APIs will be using in the future as the preferred format?
