### ISSUE TITLE
Change references of Shared Secret to Signature Secret

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-php#4]
It's possible that the API Secret and Shared Secret could be confused. Signature Secret defines exactly what that secret is used for; for signing and for checking signatures.

We could call is request signature secret to be event clearer?

**Comment by tjlytle** [comment]
[Docs call it 'security_secret'](https://docs.nexmo.com/messaging/signing-messages), so maybe that? 

I think I used shared secret because [that's the generic term](https://en.wikipedia.org/wiki/Shared_secret), I think it's called that in the dashboard, but probably just the admin dashboard.

In the code, you'd do either:

    $client = new Client(new Basic('key', 'secret'));

or 

    $client = new Client(new SharedSecret('key', 'secret'));

Perhaps `Basic` should change to be more specific. `ApiCredentials`?

**Comment by leggetter** [comment]
> Docs call it 'security_secret', so maybe that?

They do. But when I spoke to @reuvensh and we did some analysis (available on the wiki) we agreed that it was confusing to have an API Secret and a Shared Secret.

The "Shared" doesn't indicate what it's to be used for or who it's shared with. "Signature" makes it clear that it's used with signatures so I'd suggest we update the documentation to match that too. @iain-cox do you agree?

We did look at other potential names (token, key etc.), but "Signature Secret" seemed to fit best.

Since the docs are the only place where this is presently mentioned (it's not in the dashboard yet) it's just a simple update to make this change.
